### ISSUE TITLE
Error creating revision

### ISSUE THREAD

**Issue by oskarrough** [lucasmotta/dploy#32]
I'm getting the following error message when running `$ dploy`

```
Connecting to stage...
Checking revisions...

/usr/local/lib/node_modules/dploy/lib/deploy.js:321
   return console.log("Error creating revision file at:".red, ("" + revisionPa
                                                                    ^
ReferenceError: revisionPath is not defined
    at /usr/local/lib/node_modules/dploy/lib/deploy.js:321:80
    at fs.js:944:21
    at Object.oncomplete (fs.js:107:15)
```

My dploy.yaml looks like this:

```
stage:
    scheme: ftp
    host: ***
    port: 21
    user: ***
    pass: ***
    check: false
    path:
        local: build/
        remote: /
```
