### ISSUE TITLE
Deploy fails: Error: EISDIR, read

### ISSUE THREAD

**Issue by tormjens** [lucasmotta/dploy#58]
The deploy starts out fine, but at some point it fails.

Config:

```
production:
    scheme: "ftp"
    host: "****"
    user: "***"
    pass: "****"
    path:
        local: "/"
        remote: "/*****/wp-content/*****/smart-people"
    exclude: ["deploy/*.yaml", "deploy/*.json", "deploy/path/**/*.js", "deploy/**/*.md"]
```

I get the following output after running `dploy`:

```
dploy
Connecting to warehouse...
Checking revisions...
Uploading files...
[ + ] File uploaded: admin/index.php:
[ + ] File uploaded: admin/metabox/fields.php:
[ + ] File uploaded: assets/css/index.php:
[ + ] File uploaded: assets/img/index.php:
[ + ] File uploaded: assets/js/index.php:
[ + ] File uploaded: assets/third-party/index.php:
[ + ] File uploaded: assets/third-party/plugin-updates/README.md:
[ + ] File uploaded: assets/third-party/plugin-updates/css/puc-debug-bar.css:
[ + ] File uploaded: assets/third-party/plugin-updates/debug-bar-panel.php:
[ + ] File uploaded: assets/third-party/plugin-updates/debug-bar-plugin.php:
[ + ] File uploaded: assets/third-party/plugin-updates/js/debug-bar.js:
[ + ] File uploaded: assets/third-party/plugin-updates/plugin-update-checker.php:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EISDIR, read
```

I've tried running as root, changing the remote folder and deploying to a different server, but nothing seems to work.

Please help me!

Thanks.
