### ISSUE TITLE
Stops in Checking revisions step

### ISSUE THREAD

**Issue by luchiniii** [lucasmotta/dploy#59]
Hello

I´m trying to deploy a git project from my windows pc, and I'm getting:

Checking revisions...

And then, nothing.

I guess it could be the path to local repository, all the examples you have are made for linux or mac, I think, but what about windows, I'm using

C:\Users\luipalme\Documents\GitHub\nodejs

as local path. Can this be the problem?

thanks for reading

**Comment by Awea** [comment]
I got the same issue on OS X with almost the latest version of everything:

* OS X 10.10.4
* Nodejs 0.10.32
* dploy 1.2.0

Using this config file : 

```
dev:
    scheme: ftp
    host: host.com
    port: 21
    user: bar
    pass: foo
    check: true
    path:
        local: "public/wp-content/themes/8wordpress/"
        remote: "wp-content/themes/8wordpress/"
```

But it's stuck at `Checking revisions...` when I do a `dploy dev -c`
