### ISSUE TITLE
Use of patterns matching in the branch option

### ISSUE THREAD

**Issue by xavhan** [lucasmotta/dploy#65]
I'm a user of [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/), and i wanted to set my dploy config file like that : 

``` yaml
dev:
    scheme: ftp
    host: ftp.my-dev-server.com
    port: 21
    user: user
    pass: password
    branch: 
        - master
        - release/*
    path:
        local: dist/
        remote: public_html/

prod:
    scheme: ftp
    host: ftp.my-prod-server.com
    port: 21
    user: user
    pass: password
    branch: master
    path:
        local: dist/
        remote: public_html/
```

But it seems that it is impossible to use pattern matching in branches name. 

Is my syntax bad or did i try to do something that is impossible?
